version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "90:90"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    build: ./docker/php
    container_name: php
    environment:
      PHP_IDE_CONFIG: "serverName=flowbuilder"
    volumes:
      - ./:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  cron:
    build: ./docker/cron
    container_name: cron
    volumes:
      - ./:/app
    depends_on:
      - php

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: database
    environment:
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
